apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-application
    appstudio.openshift.io/component: devfile-sample-go-basic-gzlp
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-go-basic-gzlp
  namespace: jephilli
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_jeff-phillips-18_devfile-sample-go-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/jeff-phillips-18/devfile-sample-go-basic
